// <auto-generated />
using System;
using ISAS_Project.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISAS_Project.Migrations
{
    [DbContext(typeof(ISASDbContext))]
    [Migration("20240609173003_updated_table")]
    partial class updated_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ISAS_Project.Models.BiologicalTrace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("BiologicalTraces");
                });

            modelBuilder.Entity("ISAS_Project.Models.Evidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeOfExtraction")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Evidences");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Evidence");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ISAS_Project.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("MentalState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Past")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Residence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ISAS_Project.Models.Statement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeOfReceipt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Declarations");
                });

            modelBuilder.Entity("ISAS_Project.Models.BiologicalEvidence", b =>
                {
                    b.HasBaseType("ISAS_Project.Models.Evidence");

                    b.Property<string>("ExtractionTechnique")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("BiologicalEvidence");
                });

            modelBuilder.Entity("ISAS_Project.Models.PhysicalEvidence", b =>
                {
                    b.HasBaseType("ISAS_Project.Models.Evidence");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DangerLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasBiologicalTraces")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresExamination")
                        .HasColumnType("bit");

                    b.Property<bool>("UsedInCrime")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("PhysicalEvidence");
                });

            modelBuilder.Entity("ISAS_Project.Models.Suspect", b =>
                {
                    b.HasBaseType("ISAS_Project.Models.Person");

                    b.Property<string>("Suspicion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Suspect");
                });

            modelBuilder.Entity("ISAS_Project.Models.Victim", b =>
                {
                    b.HasBaseType("ISAS_Project.Models.Person");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Victim");
                });

            modelBuilder.Entity("ISAS_Project.Models.Witness", b =>
                {
                    b.HasBaseType("ISAS_Project.Models.Person");

                    b.Property<bool>("IsMonitored")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuspected")
                        .HasColumnType("bit");

                    b.Property<string>("RelationshipWithVictim")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Witness");
                });

            modelBuilder.Entity("ISAS_Project.Models.BiologicalTrace", b =>
                {
                    b.HasOne("ISAS_Project.Models.Person", "Person")
                        .WithMany("BiologicalTraces")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ISAS_Project.Models.Evidence", b =>
                {
                    b.HasOne("ISAS_Project.Models.Person", "Person")
                        .WithMany("Evidences")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ISAS_Project.Models.Statement", b =>
                {
                    b.HasOne("ISAS_Project.Models.Person", "Person")
                        .WithMany("Declarations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ISAS_Project.Models.Person", b =>
                {
                    b.Navigation("BiologicalTraces");

                    b.Navigation("Declarations");

                    b.Navigation("Evidences");
                });
#pragma warning restore 612, 618
        }
    }
}
