name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  # Specify the .NET version

    - name: Restore dependencies
      run: dotnet restore ISAS_Project/ISAS_Project/ISAS_Project.csproj

    - name: Build
      run: dotnet build ISAS_Project/ISAS_Project/ISAS_Project.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test ISAS_Project/ISAS_Project/ISAS_Project.csproj --no-build --verbosity normal

